spring.application.name=order-service

server.port=${PORT:8080}

# TODO
logging.structured.format.console=gcp

# Actuator ? health endpoint used by Cloud Run health checks
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.info.env.enabled=true

info.app.name=order-service
info.app.version=1.0.0